services:
  mysql:
    image: mysql:8.0
    container_name: gamers-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "${DB_PORT}:3306"
    networks:
      - gamers-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  redis:
    image: redis:7-alpine
    container_name: gamers-redis
    env_file:
      - .env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_DB: ${REDIS_DB}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - gamers-network
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    container_name: gamers-rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
      TZ: "Asia/Tokyo"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - gamers-network
  web-app:
    image: ghcr.io/for-gamers/gamers-be:latest
    container_name: gamers-web-server
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - gamers-network
  discord-bot:
    image: ghcr.io/for-gamers/gamers-bot:latest
    container_name: gamers-discord-bot
    env_file:
      - .env
    networks:
      - gamers-network

networks:
  gamers-network:
    external: true

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data: